application: victorique-demo
version: 1
runtime: python27
api_version: 1
threadsafe: yes


skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?\.DS_Store
- ^(.*/)?tests/.*
- ^(.*/)?test\.py
- ^README\.md
- ^\.gitignore
- ^\.gitmodules
- ^\.git/.*
- ^bower\.json
- ^package\.json
- ^pip_requirements\.txt
- ^\node_modules/.*
- ^\.idea/.*
- ^_images/.*
- ^(.*/)?.*\.coffee
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.sass
- ^(.*/)?.*\.rb
- ^\.sass-cache/.*


handlers:
# icon
- url: /favicon\.ico
  static_files: application/frontend/icons/favicon.ico
  upload: application/frontend/icons/favicon\.ico
# font
- url: /fonts/
  static_dir: application/frontend/fonts
# images
- url: /images/
  static_dir: application/frontend/images
# CSS
- url: /css/
  static_dir: application/frontend/css
# JavaScript
- url: /javascript/
  static_dir: application/frontend/javascript
# Angular Templates
- url: /views/
  static_dir: application/frontend/views

- url: .*
  script: application.app
